// AUTO-GENERATED by scripts/gen-base-path.mjs — do not edit manually.
export const BASE_PATH = "";

export function asset(path: string): string {
  if (!path.startsWith("/")) path = "/" + path;
  return BASE_PATH + path;
}
